In [ ]:
list=[1,2,3,4]
print(list)
print(type(list))

[1, 2, 3, 4]
<class 'list'>


In [ ]:
import numpy as np
x=np.array(list)
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
l=[]
for i in range(1,5):
    int_1=input("enter:")
    l.append(int_1)
print(l)
print(np.array(l))
y=np.array(l,ndmin=10)
print(y)


enter:23
enter:12
enter:45
enter:23
['23', '12', '45', '23']
['23' '12' '45' '23']
[[[[[[[[[['23' '12' '45' '23']]]]]]]]]]


In [ ]:
l1=np.zeros(4)
l2=np.zeros((3,4))
l3=np.ones((3,4))
l4=np.eye(4,3)
l5=np.linspace(0,10,5)
print(l1)
print(l2)
print(l3)
print(l4)
print(l5)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[ 0.   2.5  5.   7.5 10. ]


Random functions


In [ ]:
l1=np.random.rand(3)
l2=np.random.rand(3,3)
l3=np.random.randn(3,3)
l4=np.random.randint(10,40,7)
print(l1)
print(l2)
print(l3)
print(l4)

[0.53462257 0.88856837 0.71702501]
[[0.82605713 0.47947264 0.42278787]
 [0.03857339 0.43633801 0.97475119]
 [0.76314147 0.06666513 0.29156793]]
[[ 1.52853408 -1.30064073  1.28651382]
 [-0.53028422  0.24724569 -0.65017135]
 [ 0.3070336   0.19369646  0.1796512 ]]
[24 14 39 38 17 34 23]


Data type as functions

In [ ]:
x=np.array([1,2,3,4])
new=np.float32(x)

print(x.dtype)
print(new.dtype)

int64
float32


In [ ]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
var=var1+3
var4=var1+var2
np.add(var1,var2)
print(var)
print(var4)
print(np.multiply(var1,var2))
print(np.power(var1,var2))


[4 5 6 7]
[2 4 6 8]
[ 1  4  9 16]
[  1   4  27 256]


In [ ]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[1,2,3,4]])
print(np.add(var1,var2))
print(var1.shape)

[[2 4 6 8]
 [2 4 6 8]]
(2, 4)


#  **Pandas **

In [ ]:
data={
    "name":["sachin","david","yuvraj","viru"],
    "age":[12,34,12,45],
    "avg":[34,56,23,56],
    "city":["harayan","delhi","mombai","pune"]
}
print(data)

{'name': ['sachin', 'david', 'yuvraj', 'viru'], 'age': [12, 34, 12, 45], 'avg': [34, 56, 23, 56], 'city': ['harayan', 'delhi', 'mombai', 'pune']}


In [ ]:
import pandas as pd
df=pd.DataFrame(data)
print(df)

     name  age  avg     city
0  sachin   12   34  harayan
1   david   34   56    delhi
2  yuvraj   12   23   mombai
3    viru   45   56     pune


In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
#first five rows
print(df.head())

     name  age  avg     city
0  sachin   12   34  harayan
1   david   34   56    delhi
2  yuvraj   12   23   mombai
3    viru   45   56     pune


In [ ]:
#last five row
print(df.tail())

     name  age  avg     city
0  sachin   12   34  harayan
1   david   34   56    delhi
2  yuvraj   12   23   mombai
3    viru   45   56     pune


In [ ]:
#infomation of frame
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    4 non-null      object
 1   age     4 non-null      int64 
 2   avg     4 non-null      int64 
 3   city    4 non-null      object
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes
None


In [ ]:
#describe the frame
print(df.describe())

         age    avg
count   4.00   4.00
mean   25.75  42.25
std    16.50  16.50
min    12.00  23.00
25%    12.00  31.25
50%    23.00  45.00
75%    36.75  56.00
max    45.00  56.00


direct access , using loc and using iloc

In [ ]:
from os import name
print(df['name'])

0    sachin
1     david
2    yuvraj
3      viru
Name: name, dtype: object


In [ ]:
print(df['name'][2])

yuvraj


In [ ]:
print(df['name'][0:2])

0    sachin
1     david
Name: name, dtype: object


In [ ]:
print(df.loc[0])

name     sachin
age          12
avg          34
city    harayan
Name: 0, dtype: object


In [ ]:
print(df.loc[2,['name']])

name    yuvraj
Name: 2, dtype: object


In [ ]:
#using iloc
print(df.iloc[2])

name    yuvraj
age         12
avg         23
city    mombai
Name: 2, dtype: object


Series : One dimensional

In [ ]:
print(type(df['name']))

<class 'pandas.core.series.Series'>


In [ ]:
#adding column
df["matches"]=[12,34,55,21]
print(df)

     name  age  avg     city  No_Of_matches  matches
0  sachin   12   34  harayan             12       12
1   david   34   56    delhi             34       34
2  yuvraj   12   23   mombai             55       55
3    viru   45   56     pune             21       21


In [ ]:
#dropping a column
df=df.drop('avg',axis=1)
print(df)

     name  age     city  No_Of_matches  matches
0  sachin   12  harayan             12       12
1   david   34    delhi             34       34
2  yuvraj   12   mombai             55       55
3    viru   45     pune             21       21


In [ ]:
print(df)

     name  age     city  No_Of_matches  matches
0  sachin   12  harayan             12       12
1   david   34    delhi             34       34
2  yuvraj   12   mombai             55       55
3    viru   45     pune             21       21


In [ ]:
#adding a new row
df.loc[0]=["akshay",12,"mumbai",12,89]
print(df)

     name  age    city  No_Of_matches  matches
0  akshay   12  mumbai             12       89
1   david   34   delhi             34       34
2  yuvraj   12  mombai             55       55
3    viru   45    pune             21       21


In [ ]:
df.loc[4]=["akshit",12,"dharavi",12,34]
print(df)

     name  age     city  No_Of_matches  matches
0  akshay   12   mumbai             12       89
1   david   34    delhi             34       34
2  yuvraj   12   mombai             55       55
3    viru   45     pune             21       21
4  akshit   12  dharavi             12       34


In [ ]:
#checking whether cloumn has null value
print(df.isnull())

    name    age   city  No_Of_matches  matches
0  False  False  False          False    False
1  False  False  False          False    False
2  False  False  False          False    False
3  False  False  False          False    False
4  False  False  False          False    False


In [ ]:
print(df.isnull().sum())

name             0
age              0
city             0
No_Of_matches    0
matches          0
dtype: int64


In [ ]:
#for dropping null values
df=df.dropna()
print(df)

   age     city  No_Of_matches  matches
a   12   mumbai             12       89
b   34    delhi             34       34
c   12   mombai             55       55
d   45     pune             21       21
e   12  dharavi             12       34


In [ ]:
#changing the index
df.index = list("abcde")
print(df)


   age     city  No_Of_matches  matches
a   12   mumbai             12       89
b   34    delhi             34       34
c   12   mombai             55       55
d   45     pune             21       21
e   12  dharavi             12       34


In [ ]:
#setting index as name
df["name"]=["Vijit","Yuvaraj","Akshit","Akshay","Vatsal"]
print(df)
df=df.set_index("name")
print(df)

         age     city  No_Of_matches  matches     name
name                                                  
Vijit     12   mumbai             12       89    Vijit
Yuvaraj   34    delhi             34       34  Yuvaraj
Akshit    12   mombai             55       55   Akshit
Akshay    45     pune             21       21   Akshay
Vatsal    12  dharavi             12       34   Vatsal
         age     city  No_Of_matches  matches
name                                         
Vijit     12   mumbai             12       89
Yuvaraj   34    delhi             34       34
Akshit    12   mombai             55       55
Akshay    45     pune             21       21
Vatsal    12  dharavi             12       34


In [ ]:
#coverting to csv
df.to_csv("test.csv")

In [ ]:
#reading the csv file
df1=pd.read_csv("test.csv")
print(df1)

      name  age     city  No_Of_matches  matches
0    Vijit   12   mumbai             12       89
1  Yuvaraj   34    delhi             34       34
2   Akshit   12   mombai             55       55
3   Akshay   45     pune             21       21
4   Vatsal   12  dharavi             12       34


In [ ]:
#using Numpy
import numpy as np
df2=pd.DataFrame(np.random.rand(300,5),columns=list("abcde"))
print(df2)

            a         b         c         d         e
0    0.958904  0.183272  0.664788  0.739625  0.755194
1    0.535204  0.802095  0.553758  0.876144  0.132901
2    0.194906  0.734357  0.409605  0.878203  0.134531
3    0.201414  0.879388  0.275590  0.242498  0.116453
4    0.809280  0.661066  0.889048  0.298212  0.553367
..        ...       ...       ...       ...       ...
295  0.678536  0.104154  0.436757  0.396632  0.338546
296  0.069362  0.667531  0.259903  0.415993  0.859567
297  0.784392  0.291489  0.902015  0.435381  0.038273
298  0.354254  0.167469  0.618837  0.549057  0.977632
299  0.421881  0.543138  0.802060  0.186077  0.683533

[300 rows x 5 columns]


In [ ]:
print(df2.describe())

                a           b           c           d           e
count  300.000000  300.000000  300.000000  300.000000  300.000000
mean     0.487734    0.477258    0.506072    0.510053    0.496142
std      0.287050    0.293579    0.281420    0.286637    0.274496
min      0.000212    0.000369    0.001788    0.003414    0.009308
25%      0.248655    0.209596    0.286774    0.273897    0.263001
50%      0.466306    0.462064    0.521653    0.504168    0.506254
75%      0.731248    0.736712    0.746183    0.768234    0.718987
max      0.994169    0.993525    0.999656    0.993787    0.991043
