In [ ]:
import numpy as np

ARRAY Creation

In [5]:
zero=np.zeros((2,3)) #fill the array with zeros
one=np.ones((2,3)) #fill the array with ones
arrange=np.arange(0,10,2) # arrange the values
linspace=np.linspace(0,10,6) #spread the values in inclusive range of first two parimeter
full=np.full((2,3),5) #fill the array with a particular value
print(zero)
print("\n")
print(one)
print("\n")
print(arrange)
print("\n")
print(linspace)
print("\n")
print(full)

[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]]


[0 2 4 6 8]


[ 0.  2.  4.  6.  8. 10.]


[[5 5 5]
 [5 5 5]]


RESHAPING THE ARRAYS

In [ ]:
array=np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [ ]:
flattened=array.flatten()
transpose=array.T
reshaped=array.reshape((2,3))
print(flattened)
print("\n")
print(transpose)
print("\n")
print(reshaped)

[1 2 3 4 5 6]


[[1 4]
 [2 5]
 [3 6]]


[[1 2 3]
 [4 5 6]]


JOINING THE ARRAYS

In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[7,8],[9,10]]) #for axis=1 ie horizontal concatenation size must be same
concat=np.concatenate((arr1,arr2),axis=0)
print(concat)
vstack=np.vstack((arr1,arr2)) #same as axis=0
hstack=np.hstack((arr1,arr2)) #same as axis=1
print("\n")
print(vstack)
print("\n")
print(hstack)


[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]]


[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]]


[[ 1  2  7  8]
 [ 3  4  9 10]]


SPLITTING THE ARRAYS

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split into 3 equal parts along axis 0
split = np.split(arr, 3, axis=0)  # [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

# Horizontal split into 3 columns
hsplit = np.hsplit(arr, 3)  # [array([[1], [4], [7]]), array([[2], [5], [8]]), array([[3], [6], [9]])]

print(split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [3]:
import time
import numpy as np
start=time.time()
arr=[1,2,3]
temp=[i*2 for i in range(100000)]
print("\nList operation time",time.time()-start)
start=time.time()
arr=np.array([1,2,3])
temp=arr*2
print("\nArray operation time",time.time()-start)



List operation time 0.005682945251464844

Array operation time 0.001070261001586914


## Random


In [7]:
#inside the random class there are so many method
random=np.random.random([2,3])
print(random)
#using arange we have non inclusive values

[[0.33140018 0.901165   0.77708858]
 [0.87271719 0.36888684 0.77759128]]


## Vector , Matrix and Tensor

In [8]:
vector=np.array([1,2,3])
matrix=np.array([[1,2,3],[4,5,6]])
tensor=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(vector)
print("\n")
print(matrix)
print("\n")
print(tensor) #quite have to manupulate

[1 2 3]


[[1 2 3]
 [4 5 6]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Properties of Array

In [16]:
arr=np.array([[1,2,3],[4,5,9]]) #Similar Datatype
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


## Array Reshaping


In [25]:
arr=np.arange(0,12)
print(arr)
reshaped=arr.reshape((6,2))
print(reshaped)
flatten=reshaped.flatten()
print(flatten)
raveled=reshaped.ravel()
print(raveled) #return view instead of copy
transpose=reshaped.T;
print(transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


#indexing and slicing using Numpy

In [26]:
import numpy as np


In [33]:
arr=np.arange(0,12)
print(arr)

arr1=arr.reshape((3,4))
print(arr1)

print(arr1[1,2])
print(arr1[0:2,1:3])
print(arr1[:,2])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[[1 2]
 [5 6]]
[ 2  6 10]


## Sorting

In [38]:
unsorted_arr=np.array([3,1,5,2,1,6,7,3,2])
print(np.sort(unsorted_arr))

arr_2d_unsorted=np.array([[3,2],[3,5],[9,8]])
print(np.sort(arr_2d_unsorted,axis=0)) # when 0 (top to bottom)  1 (left to right)

[1 1 2 2 3 3 5 6 7]
[[3 2]
 [3 5]
 [9 8]]


## Filtering

In [41]:
numbers=np.arange(1,10)
print(numbers)
even=numbers[numbers%2==0]
print(even)
## with mask

mask=numbers>5
print("Number greater than five ",numbers[mask])

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]
Number greater than five  [6 7 8 9]


Fancy Indexing Vs np.where

In [53]:
number=np.arange(1,10)
indices=[0,2,4]
print(number[indices])
print(number[np.where(number>5)])

conArray=np.where(number>5,number%2,number) ## where(if condition , if block , else block )
print(conArray)

[1 3 5]
[6 7 8 9]
[1 0 1 0 5 0 1 0 1]


## Adding and Removing Data

In [64]:
arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6,7])
combine=arr1+arr2
print(combine)
conCat=np.concatenate((arr1,arr2))
print(conCat)

print("Compatability Shape ",arr1.shape==arr2.shape)

# Adding new rows

new_row=np.array([10,11,12,13])
with_new_row=np.vstack((arr1,new_row))
print(with_new_row)
new_col=np.array([[10],[11]])
with_new_col=np.hstack((with_new_row,new_col))
print(with_new_col)

[ 5  7  9 11]
[1 2 3 4 4 5 6 7]
Compatability Shape  True
[[ 1  2  3  4]
 [10 11 12 13]]
[[ 1  2  3  4 10]
 [10 11 12 13 11]]
