**NumPy** (Numerical Python) is the foundational open-source library for scientific computing in Python. It provides a high-performance multidimensional array object, known as ndarray, along with tools for working with these arrays. NumPy is widely used to efficiently store and manipulate dense data buffers, making it the backbone of the Python data science ecosystem, including libraries like Pandas, SciPy, and Scikit-learn.

**Why NumPy is Used**

NumPy is preferred over standard Python lists for numerical data because it is much faster and more memory-efficient. Key reasons include:

* **Performance (Speed)**: NumPy arrays are stored in contiguous memory locations, allowing processes to access and manipulate them up to 50x faster than traditional Python lists.

* **Vectorization**: NumPy allows mathematical operations on whole arrays without needing explicit for loops, which results in faster execution and cleaner code.
Homogeneous Data Types: NumPy arrays restrict elements to the same data type, which reduces memory overhead and allows the library to pre-compile optimized C code to perform operations.

* **Broadcasting**: NumPy can perform arithmetic operations on arrays of different shapes, which simplifies coding.

* **Functionality**: It includes a comprehensive library of mathematical functions, including linear algebra, Fourier transforms, and random number generation.









In [2]:
import numpy as np


In [5]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [6]:
## dimension and shape of array
print(arr.ndim)
arr1=np.array(10) # without braces its a scalar value
print(arr1.ndim)
a=np.array([[],[],[]])
print(a.ndim)
print(a.shape)


1
0
2
(3, 0)


Some BuiltIn Function

In [7]:
# Inbuilt function

#1. Range
arr=np.arange(0,10) # (inclusive,exclusive,skip)
print(arr)
#2. linspace
arr=np.linspace(0,1,1)
print(arr)
#3. logspace
arr=np.logspace(1,3,3) # (start, ending->power,3->number of values)
print(arr)
#4. zeros
arr=np.zeros([2,3])
print(arr)
#5. ones
arr=np.ones([2,3])
print(arr)
#6. full
arr=np.full([2,3],10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]
[0.]
[  10.  100. 1000.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[10 10 10]
 [10 10 10]]


In [8]:
#uninitialised array
arr=np.empty([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


Random Sub Module

In [9]:
#Random Functions in NumPy
# Random is a package inside the Numpy library
arr=np.random.rand(10)
print(arr)
arr=np.random.randn(2,3)
print(arr)
arr=np.random.randint(2,3) #start, stop , dimension
print(arr)
arr=np.random.randint(2,100,[2,3]) #start, stop , dimension
print(arr)


[0.78294703 0.09678789 0.62568814 0.05736382 0.23468195 0.85079685
 0.02724976 0.53104696 0.65584088 0.27531598]
[[ 1.89990844  1.21388563  0.419114  ]
 [ 0.27550181  0.24176398 -0.02124382]]
2
[[83 50 66]
 [ 8 31  4]]


Numpy DataTypes and TypeCasting

In [10]:
arr=np.array([1,2,3.1,4]) #converted to float
print(arr)
print(arr.dtype) #in float, float64 is by default
lst=[1,2,3,4.5]
arr=np.array(lst,dtype=np.int64) #elements converted to string
print(arr)
print(arr.dtype)
arr=np.array([1,2,3,4],dtype=np.float128)
print(arr)

#type casting is done using astype()

arr=np.array([1,2,3])
print(arr.dtype)
arr=arr.astype(np.float128)
print(arr)
print(arr.dtype)
arr=arr.astype(np.int64)
print(arr)


#we get type casting error in case of failure in casting
#string to integer


[1.  2.  3.1 4. ]
float64
[1 2 3 4]
int64
[1. 2. 3. 4.]
int64
[1. 2. 3.]
float128
[1 2 3]


Multidimensional

In [11]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


Array Re-shaping

In [12]:
#changing the structure of the array without changing the data
arr=np.array([1,2,3,4,5,6])
arr=arr.reshape([2,3])
print(arr)
arr=arr.reshape([3,2])
print(arr)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [13]:
#Ravel converting any dimensional data to one dimensional
arr=np.array([1,2,3,4,5,6])
arr=arr.reshape([2,3])
print(arr)
one_d=arr.ravel()
print("ravel",one_d)
flatten=arr.flatten()
print("flatten",flatten)

# ravel have changes on og array and flatten returns the copy

[[1 2 3]
 [4 5 6]]
ravel [1 2 3 4 5 6]
flatten [1 2 3 4 5 6]


Arithematic operation on arrays

In [14]:
a=np.array([1,20,3])
b=np.array([1,2,8])
c=a+b*(-1) #addtion and substraction and mutiplication
print(c,c.dtype)
print(a//b)
print(a%b)
print(a**b)

[ 0 18 -5] int64
[ 1 10  0]
[0 0 3]
[   1  400 6561]


Universal Function

In [15]:
arr=np.array([1,4,9,16],dtype=np.int16)
print(np.sqrt(arr))
print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))
angle=np.array([0,np.pi,np.pi//2])
print(np.sin(angle))
print(np.cos(angle))
print(np.tan(angle))


[1. 2. 3. 4.]
[0.        1.3862944 2.1972246 2.7725887]
[0.        0.60206   0.9542425 1.20412  ]
[2.718282e+00 5.459815e+01 8.103084e+03 8.886111e+06]
[0.00000000e+00 1.22464680e-16 8.41470985e-01]
[ 1.         -1.          0.54030231]
[ 0.00000000e+00 -1.22464680e-16  1.55740772e+00]


Indexing and slicing

---




In [26]:
arr=np.array([1,2,3,4])
print(arr[::2])
#negative indexing
print(arr[-1])
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:2,:2])

[1 3]
4
[[1 2]
 [4 5]]


In [4]:
#Index-> Array

#np.take
arr=np.array([10,20,30,40])
print(np.take(arr,[0,2,3]))


[10 30 40]


In [6]:
#iterating with nditer

arr=np.array([[1,2],[4,5]])
for x in np.nditer(arr):
  print(x)
for i,x in np.ndenumerate(arr):
  print(i,x)

1
2
4
5
(0, 0) 1
(0, 1) 2
(1, 0) 4
(1, 1) 5


In [16]:
#views vs copy
#in view Og array is affected
#in copies no effect on og array
arr=np.array([1,2,3,4])
view=arr[0:2]
view[0]=1000
view
arr

copy=arr[1:3].copy()
copy[0]=1000
copy
arr

array([1000,    2,    3,    4])

In [21]:
#Transpose
arr=np.array([[1,2,3],[4,5,6]])
print(arr.transpose())
#Swap axis
print(arr.shape)
swap=np.swapaxes(arr,0,1)
print(swap.shape)

[[1 4]
 [2 5]
 [3 6]]
(2, 3)
(3, 2)


In [24]:
#concatenate
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(np.concatenate((arr1,arr2),axis=1))
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))
print(np.split(arr1,2,axis=0))
print(np.split(arr1,3,axis=1))
# we can use stack axix=0 (row) and axis=1 (column)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [31]:
#repeating
arr=np.array([[10,20],[30,40]])
print(np.repeat(arr,2))
print(np.tile(arr,2))
# Conditioning in Array
res=np.where(arr<=20, "Low","high")
res1=np.logical_and(arr>=20,arr<=30)
print(res)
print(res1 )
print(arr[res1])

[10 10 20 20 30 30 40 40]
[[10 20 10 20]
 [30 40 30 40]]
[['Low' 'Low']
 ['high' 'high']]
[[False  True]
 [ True False]]
[20 30]


In [9]:
#broadcasting

arr=np.array([[100,200],[300,400]])
arr=arr+50
arr


array([[150, 250],
       [350, 450]])

In [10]:
#vectorization
# np.vectorize converst regular function to be applied on an array
def square(x):
  return x*x
vfunc=np.vectorize(square)
arr=np.array([10,11,12,13])
print(vfunc(arr))

[100 121 144 169]


In [15]:
# Dealing with missing value
#np.nan
arr=np.array([1,2,3,np.nan,5])
#checking for any
print(np.isnan(arr))
#isinf
#np.nan_to_num  in order to convert the infinity to numbers


[False False False  True False]
